---
title: "resistance"
author: "Maxwel Coura Oliveira"
date: "3/2/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ragg)
library(colorspace)
```


```{r}
library(rvest)
library(tidyverse)
```

```{r word-resistance}
world_res <- read_html("http://weedscience.org/Summary/CountrySummary.aspx")

resistance_chart <- world_res %>% 
    html_node("table") %>% 
    html_table(fill = TRUE, header = TRUE)

resistance_chart %>% 
  janitor::row_to_names(row_number = 1) %>% 
  as_tibble() %>% 
  pivot_longer(cols = A:Other, names_to = "SOA", values_to = "Number")
```


```{r}
usa_res <- read_html("http://weedscience.org/Summary/Country.aspx?CountryID=45")

usa_chart <- usa_res %>% 
    html_node(".rgMasterTable") %>% 
    html_table(fill = TRUE, header = FALSE)

final_usa_chart <- usa_chart %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  as_tibble() %>% 
  drop_na() %>% 
  dplyr::select(-x)
```


```{r brazil}
bra_res <- read_html("http://weedscience.org/Summary/Country.aspx?CountryID=5")

bra_chart <- bra_res %>% 
    html_node(".rgMasterTable") %>% 
    html_table(fill = TRUE, header = FALSE)

final_bra_chart <- bra_chart %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  as_tibble() 
```


```{r}
tfile = tempfile(fileext=".html")
download.file("http://youtube.com/", tfile)
rstudioapi::viewer(tfile)
```

```{r brazil}
species <- read_html("http://weedscience.org/Summary/Species.aspx")
```


```{r brazil}
sp_chart <- species %>% 
    html_node("table") %>% 
    html_table(fill = TRUE, header = FALSE)
```


```{r brazil}
final_bra_chart <- bra_chart %>% 
  janitor::row_to_names(row_number = 2) %>% 
  janitor::clean_names() %>% 
  as_tibble() 
```